version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mediateca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mediateca_db
    ports:
      - "3306:3306"
    volumes:
      - mediateca_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mediateca_data: